name: Integration Pipeline
on:
  workflow_dispatch:
  pull_request:
    branches: [develop, main]

concurrency:
  group: build-${{ github.ref || github.run_id }}

jobs:
  integration_pipeline:
    name: integration_pipeline
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.1"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "sudo build_and_copy.sh debug"
        run: |
          ./pipelines/build_and_copy.sh debug
        shell: bash

      - name: "validate.sh"
        run: |
          ./pipelines/validate.sh
        shell: bash
